In [1]:
#libraries
import pandas as pd
import numpy as np

In [2]:
#options
pd.set_option('display.max_columns', None)

In [3]:
from pydataset import data
mtcars=data("mtcars")
mtcars.head(5)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [4]:
','.join(data()['dataset_id'])

'AirPassengers,BJsales,BOD,Formaldehyde,HairEyeColor,InsectSprays,JohnsonJohnson,LakeHuron,LifeCycleSavings,Nile,OrchardSprays,PlantGrowth,Puromycin,Titanic,ToothGrowth,UCBAdmissions,UKDriverDeaths,UKgas,USAccDeaths,USArrests,USJudgeRatings,USPersonalExpenditure,VADeaths,WWWusage,WorldPhones,airmiles,airquality,anscombe,attenu,attitude,austres,cars,chickwts,co2,crimtab,discoveries,esoph,euro,faithful,freeny,infert,iris,islands,lh,longley,lynx,morley,mtcars,nhtemp,nottem,npk,occupationalStatus,precip,presidents,pressure,quakes,randu,rivers,rock,sleep,stackloss,sunspot.month,sunspot.year,sunspots,swiss,treering,trees,uspop,volcano,warpbreaks,women,acme,aids,aircondit,aircondit7,amis,aml,bigcity,brambles,breslow,calcium,cane,capability,catsM,cav,cd4,channing,city,claridge,cloth,co.transfer,coal,darwin,dogs,downs.bc,ducks,fir,frets,grav,gravity,hirose,islay,manaus,melanoma,motor,neuro,nitrofen,nodal,nuclear,paulsen,poisons,polar,remission,salinity,survival,tau,tuna,urine,wool,aids,alloauto,allograft,azt,baboon,bcdeter,bfeed,bmt,bnct,btrial,burn,channing,drug6mp,drughiv,hodg,kidney,kidrecurr,kidtran,larynx,lung,pneumon,psych,rats,std,stddiag,tongue,twins,Animals2,CrohnD,NOxEmissions,SiegelsEx,aircraft,airmay,alcohol,ambientNOxCH,bushfire,carrots,cloud,coleman,condroz,cushny,delivery,education,epilepsy,exAM,foodstamp,hbk,heart,kootenay,lactic,milk,pension,phosphor,pilot,possumDiv,pulpfiber,radarImage,salinity,starsCYG,telef,toxicity,vaso,wagnerGrowth,wood,AMSsurvey,Adler,Angell,Anscombe,Baumann,Bfox,Blackmoor,Burt,CanPop,Chile,Chirot,Cowles,Davis,DavisThin,Depredations,Duncan,Ericksen,Florida,Freedman,Friendly,Ginzberg,Greene,Guyer,Hartnagel,Highway1,Leinhardt,Mandel,Migration,Moore,Mroz,OBrienKaiser,Ornstein,Pottery,Prestige,Quartet,Robey,SLID,Sahlins,Salaries,Soils,States,Transact,UN,USPop,Vocab,WeightLoss,Womenlf,Wool,agriculture,animals,chorSub,flower,plantTraits,pluton,ruspini,votes.repub,xclara,affairs,azcabgptca,azdrg112,azpro,azprocedure,badhealth,fasttrakg,fishing,lbw,lbwgrp,loomis,mdvis,medpar,nuts,rwm,rwm1984,rwm5yr,ships,smoking,titanic,titanicgrp,Accident,Airline,Airq,Benefits,Bids,BudgetFood,BudgetItaly,BudgetUK,Bwages,CPSch3,CRANpackages,Capm,Car,Caschool,Catsup,Cigar,Cigarette,Clothing,Computers,Cracker,Crime,DM,Diamond,Doctor,DoctorAUS,DoctorContacts,Earnings,Electricity,Fair,Fatality,Fishing,Forward,FriendFoe,Garch,Gasoline,Griliches,Grunfeld,HC,HI,Hdma,Heating,Hedonic,Housing,Icecream,Journals,Kakadu,Ketchup,Klein,LaborSupply,Labour,MCAS,Males,Mathlevel,MedExp,Metal,Mode,ModeChoice,Mofa,Mroz,MunExp,NaturalPark,Nerlove,OFP,Oil,PSID,Participation,PatentsHGH,PatentsRD,Pound,Produc,RetSchool,SP500,Schooling,Somerville,Star,Strike,StrikeDur,StrikeNb,SumHes,Tobacco,Train,TranspEq,Treatment,Tuna,USFinanceIndustry,USclassifiedDocuments,USstateAbbreviations,UStaxWords,UnempDur,Unemployment,University,VietNamH,VietNamI,Wages,Wages1,Workinghours,Yen,Yogurt,bankingCrises,incomeInequality,nonEnglishNames,politicalKnowledge,PD,aldh2,apoeapoc,cf,crohn,fa,fsnps,hla,hr1420,l51,lukas,mao,mfblong,mhtdata,nep499,diamonds,economics,midwest,movies,mpg,msleep,presidential,seals,Arbuthnot,Bowley,Cavendish,ChestSizes,CushnyPeebles,CushnyPeeblesN,Dactyl,DrinksWages,Fingerprints,Galton,GaltonFamilies,Guerry,Jevons,Langren.all,Langren1644,Macdonell,MacdonellDF,Michelson,MichelsonSets,Minard.cities,Minard.temp,Minard.troops,Nightingale,OldMaps,PearsonLee,PolioTrials,Prostitutes,Pyx,Quarrels,Snow.deaths,Snow.polygons,Snow.pumps,Snow.streets,Wheat,Wheat.monarchs,Yeast,YeastD.mat,ZeaMays,barley,environmental,ethanol,melanoma,singer,Aids2,Animals,Boston,Cars93,Cushings,DDT,GAGurine,Insurance,Melanoma,OME,Pima.te,Pima.tr,Pima.tr2,Rabbit,Rubber,SP500,Sitka,Sitka89,Skye,Traffic,UScereal,UScrime,VA,abbey,accdeaths,anorexia,bacteria,beav1,beav2,biopsy,birthwt,cabbages,caith,cats,cement,chem,coop,cpus,crabs,deaths,drivers,eagles,epil,farms,fgl,forbes,galaxies,gehan,genotype,geyser,gilgais,hills,housing,immer,leuk,mammals,mcycle,menarche,michelson,minn38,motors,muscle,newcomb,nlschools,npk,npr1,oats,painters,petrol,quine,road,rotifer,ships,shrimp,shuttle,snails,steam,stormer,survey,synth.te,synth.tr,topo,waders,whiteside,wtloss,Cigar,Crime,EmplUK,Gasoline,Grunfeld,Hedonic,LaborSupply,Males,Produc,Snmesp,SumHes,Wages,baseball,AustralianElectionPolling,AustralianElections,EfronMorris,RockTheVote,UKHouseOfCommons,absentee,admit,bioChemists,ca2006,iraqVote,politicalInformation,presidentialElections,prussian,unionDensity,vote92,french_fries,smiths,tips,car.test.frame,car90,cu.summary,kyphosis,solder,stagec,PublicSchools,Bollen,CNES,Klein,Kmenta,Tests,bladder,cancer,cgd,colon,flchain,heart,kidney,leukemia,logan,lung,mgus,nwtco,ovarian,pbc,rats,stanford2,tobin,veteran,Arthritis,Baseball,BrokenMarriage,Bundesliga,Bundestag2005,Butterfly,CoalMiners,DanishWelfare,Employment,Federalist,Hitters,HorseKicks,Hospital,JobSatisfaction,JointSports,Lifeboats,NonResponse,OvaryCancer,PreSex,Punishment,RepVict,Saxony,SexualFun,SpaceShuttle,Suicide,Trucks,UKSoccer,VisualAcuity,VonBort,WeldonDice,WomenQueue,MatchIt.url,PErisk,SupremeCourt,Weimar,Zelig.url,approval,bivariate,coalition,coalition2,eidat,free1,free2,friendship,grunfeld,hoff,homerun,immi1,immi2,immi3,immi4,immi5,immigration,klein,kmenta,macro,mexico,mid,newpainters,sanction,sna.ex,swiss,tobin,turnout,voteincome,BCG,BtheB,CYGOB1,Forbes2000,GHQ,Lanza,agefat,aspirin,birthdeathrates,bladdercancer,clouds,epilepsy,foster,heptathlon,mastectomy,meteo,orallesions,phosphate,pistonrings,planets,plasma,polyps,polyps3,pottery,rearrests,respiratory,roomwidth,schizophrenia,schizophrenia2,schooldays,skulls,smoking,students,suicides,toothpaste,voting,water,watervoles,waves,weightgain,womensrole,Bechtoldt,Bechtoldt.1,Bechtoldt.2,Dwyer,Gleser,Gorsuch,Harman.5,Harman.8,Harman.political,Holzinger,Holzinger.9,Reise,Schmid,Thurstone,Thurstone.33,Tucker,ability,affect,bfi,bfi.dictionary,blot,burt,cities,cubits,cushny,epi,epi.bfi,epi.dictionary,galton,heights,income,iqitems,msq,neo,peas,sat.act,withinBetween,Bosco,CobarOre,Mammals,barro,engel,uis,dietox,koch,ohio,respdis,respiratory,seizure,sitka89,spruce,liver,portpirie,rain,summer,wavesurge,winter,arthritis,housing,bmw,danish,nidd.annual,nidd.thresh,siemens,sp.raw,spto87,Dyestuff,Dyestuff2,InstEval,Pastes,Penicillin,VerbAgg,cake,cbpp,grouseticks,sleepstudy'

In [5]:
mtcars.sample(3)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Merc 280C      17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4

# Advanced

-Change datatypes
-encode
-row names to coloumns
-filter
-sorts
-select datatypes
-pivot
-melt
-wide

# A Dataframe with 32 observations on 11 (numeric) variables


mpg: Miles/(US) gallon
cyl: Number of cylinders
disp: Displacement (cu.in.)
hp: Gross horsepower
drat: Rear axle ratio
wt: Weight (1000 lbs)
qsec: 1/4 mile time (seconds)
vs: Engine configuration (0 = V-shaped, 1 = straight)
am: Transmission (0 = automatic, 1 = manual)
gear: Number of forward gears
carb: Number of carburetors

In [6]:
mtcars.dtypes

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [7]:
#change data types
mtcars.head(3)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710     22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

In [8]:
# Covert selected columns to category
mtcars = data('mtcars')
mtcars = mtcars.astype({'cyl':'category','vs':'category','carb':'category','am':'category','gear':'category'})

In [9]:
mtcars.dtypes

mpg      float64
cyl     category
disp     float64
hp         int64
drat     float64
wt       float64
qsec     float64
vs      category
am      category
gear    category
carb    category
dtype: object

In [10]:
mtcars.head()

                    mpg cyl   disp   hp  drat     wt   qsec vs am gear carb
Mazda RX4          21.0   6  160.0  110  3.90  2.620  16.46  0  1    4    4
Mazda RX4 Wag      21.0   6  160.0  110  3.90  2.875  17.02  0  1    4    4
Datsun 710         22.8   4  108.0   93  3.85  2.320  18.61  1  1    4    1
Hornet 4 Drive     21.4   6  258.0  110  3.08  3.215  19.44  1  0    3    1
Hornet Sportabout  18.7   8  360.0  175  3.15  3.440  17.02  0  0    3    2

In [11]:
mtcars['am'] =mtcars['am'].map({0 :'auto', 1:'manual'})
mtcars.head() #Sorting by manual to automatic engine

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,manual,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,manual,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,manual,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,auto,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,auto,3,2

In [12]:
mtcars['gear'] =mtcars['gear'].map({4 :'munira', 3:'shumi'})
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,manual,munira,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,manual,munira,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,manual,munira,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,auto,shumi,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,auto,shumi,2

In [13]:
mtcars['am'].value_counts()

am
auto      19
manual    13
Name: count, dtype: int64

In [14]:
mtcars['am'] =mtcars['am'].map({0:'shumi', 1:'munira'})
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,NaN,munira,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,NaN,munira,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,NaN,munira,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,NaN,shumi,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,NaN,shumi,2

In [15]:
mtcars['mpg'].max()

33.9

In [16]:
mtcars[mtcars['mpg'] == 33.9]

                 mpg cyl  disp  hp  drat     wt  qsec vs  am    gear carb
Toyota Corolla  33.9   4  71.1  65  4.22  1.835  19.9  1 NaN  munira    1

In [17]:
mtcars[mtcars['mpg'] > 30]

                 mpg cyl  disp   hp  drat     wt   qsec vs  am    gear carb
Fiat 128        32.4   4  78.7   66  4.08  2.200  19.47  1 NaN  munira    1
Honda Civic     30.4   4  75.7   52  4.93  1.615  18.52  1 NaN  munira    2
Toyota Corolla  33.9   4  71.1   65  4.22  1.835  19.90  1 NaN  munira    1
Lotus Europa    30.4   4  95.1  113  3.77  1.513  16.90  1 NaN     NaN    2

In [18]:
mtcars[mtcars['mpg']>30].sort_values('mpg')

                 mpg cyl  disp   hp  drat     wt   qsec vs  am    gear carb
Honda Civic     30.4   4  75.7   52  4.93  1.615  18.52  1 NaN  munira    2
Lotus Europa    30.4   4  95.1  113  3.77  1.513  16.90  1 NaN     NaN    2
Fiat 128        32.4   4  78.7   66  4.08  2.200  19.47  1 NaN  munira    1
Toyota Corolla  33.9   4  71.1   65  4.22  1.835  19.90  1 NaN  munira    1

In [19]:
mtcars[mtcars['mpg']>30].sort_values('mpg',ascending=False)

                 mpg cyl  disp   hp  drat     wt   qsec vs  am    gear carb
Toyota Corolla  33.9   4  71.1   65  4.22  1.835  19.90  1 NaN  munira    1
Fiat 128        32.4   4  78.7   66  4.08  2.200  19.47  1 NaN  munira    1
Honda Civic     30.4   4  75.7   52  4.93  1.615  18.52  1 NaN  munira    2
Lotus Europa    30.4   4  95.1  113  3.77  1.513  16.90  1 NaN     NaN    2

In [20]:
mtcars[mtcars['mpg'] == mtcars['mpg'].max()]

                 mpg cyl  disp  hp  drat     wt  qsec vs  am    gear carb
Toyota Corolla  33.9   4  71.1  65  4.22  1.835  19.9  1 NaN  munira    1

In [21]:
mtcars[mtcars['mpg'] >= mtcars['mpg'].mean()]

                 mpg cyl   disp   hp  drat     wt   qsec vs  am    gear carb
Mazda RX4       21.0   6  160.0  110  3.90  2.620  16.46  0 NaN  munira    4
Mazda RX4 Wag   21.0   6  160.0  110  3.90  2.875  17.02  0 NaN  munira    4
Datsun 710      22.8   4  108.0   93  3.85  2.320  18.61  1 NaN  munira    1
Hornet 4 Drive  21.4   6  258.0  110  3.08  3.215  19.44  1 NaN   shumi    1
Merc 240D       24.4   4  146.7   62  3.69  3.190  20.00  1 NaN  munira    2
Merc 230        22.8   4  140.8   95  3.92  3.150  22.90  1 NaN  munira    2
Fiat 128        32.4   4   78.7   66  4.08  2.200  19.47  1 NaN  munira    1
Honda Civic     30.4   4   75.7   52  4.93  1.615  18.52  1 NaN  munira    2
Toyota Corolla  33.9   4   71.1   65  4.22  1.835  19.90  1 NaN  munira    1
Toyota Corona   21.5   4  120.1   97  3.70  2.465  20.01  1 NaN   shumi    1
Fiat X1-9       27.3   4   79.0   66  4.08  1.935  18.90  1 NaN  munira    1
Porsche 914-2   26.0   4  120.3   91  4.43  2.140  16.70  0 NaN     NaN    2
Lotus Europa    30.4   4   95.1  113  3.77  1.513  16.90  1 NaN     NaN    2
Volvo 142E      21.4   4  121.0  109  4.11  2.780  18.60  1 NaN  munira    2

In [22]:
bins = [0,17,29, mtcars['mpg'].max()]
labels =['low','medium','high']

In [23]:
mtcars['mpg_level'] = pd.cut(mtcars['mpg'], bins=bins,labels=labels,include_lowest=True)

In [57]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4

In [25]:
mtcars.tail()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.9,1,NaN,NaN,2,high
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.5,0,NaN,NaN,4,low
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.5,0,NaN,NaN,6,medium
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.6,0,NaN,NaN,8,low
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.6,1,NaN,munira,2,medium

In [26]:
bins = [0,70,150,250, mtcars['hp'].max()]
labels =['low','medium','high','very high']
mtcars['hp_level'] = pd.cut(mtcars['hp'], bins=bins,labels=labels,include_lowest=True)

In [27]:
mtcars['hp'].value_counts()

hp
110    3
175    3
180    3
245    2
123    2
150    2
66     2
65     1
335    1
264    1
113    1
91     1
97     1
230    1
52     1
93     1
215    1
205    1
95     1
62     1
105    1
109    1
Name: count, dtype: int64

In [60]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4

In [29]:
mtcars.tail()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.9,1,NaN,NaN,2,high,medium
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.5,0,NaN,NaN,4,low,very high
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.5,0,NaN,NaN,6,medium,high
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.6,0,NaN,NaN,8,low,very high
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.6,1,NaN,munira,2,medium,medium

In [30]:
mtcars['gear'].value_counts()

gear
shumi     15
munira    12
Name: count, dtype: int64

In [31]:
mtcars['gear'] =mtcars['gear'].map({3:'shumi', 4:'munira'})
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,NaN,NaN,4,medium,medium
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,NaN,NaN,4,medium,medium
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,NaN,NaN,1,medium,medium
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,NaN,NaN,1,medium,medium
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,NaN,NaN,2,medium,high

In [32]:
#mtcars.groupby('mpg_level')['mpg'].count()

In [33]:
mtcars.mpg_level.value_counts()

mpg_level
medium    17
low       11
high       4
Name: count, dtype: int64

In [34]:
mtcars.describe()

             mpg        disp          hp       drat         wt       qsec   am
count  32.000000   32.000000   32.000000  32.000000  32.000000  32.000000  0.0
mean   20.090625  230.721875  146.687500   3.596563   3.217250  17.848750  NaN
std     6.026948  123.938694   68.562868   0.534679   0.978457   1.786943  NaN
min    10.400000   71.100000   52.000000   2.760000   1.513000  14.500000  NaN
25%    15.425000  120.825000   96.500000   3.080000   2.581250  16.892500  NaN
50%    19.200000  196.300000  123.000000   3.695000   3.325000  17.710000  NaN
75%    22.800000  326.000000  180.000000   3.920000   3.610000  18.900000  NaN
max    33.900000  472.000000  335.000000   4.930000   5.424000  22.900000  NaN

In [35]:
#carnames
mtcars['carnames'] = mtcars.index

In [36]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,carnames
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,NaN,NaN,4,medium,medium,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,NaN,NaN,4,medium,medium,Mazda RX4 Wag
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,NaN,NaN,1,medium,medium,Datsun 710
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,NaN,NaN,1,medium,medium,Hornet 4 Drive
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,NaN,NaN,2,medium,high,Hornet Sportabout

In [37]:
mtcars.dtypes#float,category,object(text),int

mpg           float64
cyl          category
disp          float64
hp              int64
drat          float64
wt            float64
qsec          float64
vs           category
am            float64
gear           object
carb         category
mpg_level    category
hp_level     category
carnames       object
dtype: object

In [38]:
print(len(mtcars[mtcars['mpg']>25]))
mtcars[mtcars['mpg']>25]
#list car with mileage more than 25

6

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,carnames
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,NaN,NaN,1,high,low,Fiat 128
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,NaN,NaN,2,high,low,Honda Civic
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,NaN,NaN,1,high,low,Toyota Corolla
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,NaN,NaN,1,medium,low,Fiat X1-9
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,NaN,NaN,2,medium,medium,Porsche 914-2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,NaN,NaN,2,high,medium,Lotus Europa

In [39]:
mtcars[mtcars['wt']>=5]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,carnames
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,NaN,NaN,4,low,high,Cadillac Fleetwood
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,NaN,NaN,4,low,high,Lincoln Continental
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,NaN,NaN,4,low,high,Chrysler Imperial

In [40]:
print(len(mtcars[mtcars['wt']>=5]))
mtcars[mtcars['wt']>=5]

3

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,carnames
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,NaN,NaN,4,low,high,Cadillac Fleetwood
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,NaN,NaN,4,low,high,Lincoln Continental
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,NaN,NaN,4,low,high,Chrysler Imperial

In [41]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,carnames
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,NaN,NaN,4,medium,medium,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,NaN,NaN,4,medium,medium,Mazda RX4 Wag
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,NaN,NaN,1,medium,medium,Datsun 710
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,NaN,NaN,1,medium,medium,Hornet 4 Drive
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,NaN,NaN,2,medium,high,Hornet Sportabout

In [42]:
mtcars[mtcars['mpg_level'] == 'high' ]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,carnames
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,NaN,NaN,1,high,low,Fiat 128
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,NaN,NaN,2,high,low,Honda Civic
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,NaN,NaN,1,high,low,Toyota Corolla
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,NaN,NaN,2,high,medium,Lotus Europa

In [43]:
mtcars.query("mpg<23")

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,carnames
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,NaN,NaN,4,medium,medium,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,NaN,NaN,4,medium,medium,Mazda RX4 Wag
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,NaN,NaN,1,medium,medium,Datsun 710
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,NaN,NaN,1,medium,medium,Hornet 4 Drive
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,NaN,NaN,2,medium,high,Hornet Sportabout
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,NaN,NaN,1,medium,medium,Valiant
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,NaN,NaN,4,low,high,Duster 360
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,NaN,NaN,2,medium,medium,Merc 230
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,NaN,NaN,4,medium,medium,Merc 280
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,NaN,NaN,4,medium,medium,Merc 280C
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,NaN,NaN,3,low,high,Merc 450SE
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,NaN,NaN,3,medium,high,Merc 450SL
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,NaN,NaN,3,low,high,Merc 450SLC
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,NaN,NaN,4,low,high,Cadillac Fleetwood
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,NaN,NaN,4,low,high,Lincoln Continental
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,NaN,NaN,4,low,high,Chrysler Imperial
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,NaN,NaN,1,medium,medium,Toyota Corona
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,NaN,NaN,2,low,medium,Dodge Challenger
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,NaN,NaN,2,low,medium,AMC Javelin
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,NaN,NaN,4,low,high,Camaro Z28
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,NaN,NaN,2,medium,high,Pontiac Firebird
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,NaN,NaN,4,low,very high,Ford Pantera L
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,NaN,NaN,6,medium,high,Ferrari Dino
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,NaN,NaN,8,low,very high,Maserati Bora
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,NaN,NaN,2,medium,medium,Volvo 142E

In [44]:
mtcars.filter(items=['mpg','hp'])
#list the data with columns mpg and hp

                      mpg   hp
Mazda RX4            21.0  110
Mazda RX4 Wag        21.0  110
Datsun 710           22.8   93
Hornet 4 Drive       21.4  110
Hornet Sportabout    18.7  175
Valiant              18.1  105
Duster 360           14.3  245
Merc 240D            24.4   62
Merc 230             22.8   95
Merc 280             19.2  123
Merc 280C            17.8  123
Merc 450SE           16.4  180
Merc 450SL           17.3  180
Merc 450SLC          15.2  180
Cadillac Fleetwood   10.4  205
Lincoln Continental  10.4  215
Chrysler Imperial    14.7  230
Fiat 128             32.4   66
Honda Civic          30.4   52
Toyota Corolla       33.9   65
Toyota Corona        21.5   97
Dodge Challenger     15.5  150
AMC Javelin          15.2  150
Camaro Z28           13.3  245
Pontiac Firebird     19.2  175
Fiat X1-9            27.3   66
Porsche 914-2        26.0   91
Lotus Europa         30.4  113
Ford Pantera L       15.8  264
Ferrari Dino         19.7  175
Maserati Bora        15.0  335
Volvo 142E           21.4  109

In [45]:
mtcars['am'] =mtcars['am'].map({0 :'auto', 1:'manual'})
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,carnames
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,NaN,NaN,4,medium,medium,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,NaN,NaN,4,medium,medium,Mazda RX4 Wag
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,NaN,NaN,1,medium,medium,Datsun 710
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,NaN,NaN,1,medium,medium,Hornet 4 Drive
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,NaN,NaN,2,medium,high,Hornet Sportabout

In [46]:
mtcars[mtcars['am'] == 'auto']

Empty DataFrame
Columns: [mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, carb, mpg_level, hp_level, carnames]
Index: []

In [47]:
mtcars=data("mtcars")
mtcars.head(5)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [48]:
mtcars[(mtcars['am'] == 'auto') & (mtcars['cyl'] != '5') & (mtcars['mpg'] > 22 )]
# Use & for “AND” between them. cars = auto, cyl <> 5, mpg>22 ; all 3 conditions
# in Pandas, | = OR, ~ = NOT.

Empty DataFrame
Columns: [mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, carb]
Index: []

In [49]:
mtcars[mtcars['mpg'].between(23,30,between(left=23,right=26.1,inclusive='left')] #inclusive{"both","neither","left","right"}
#car with mpg between 23 and 26

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (3875328733.py, line 1)

In [ ]:
mtcars[mtcars['mpg'].between(23,30,inclusive='neither')]

In [ ]:
mtcars[mtcars['mpg'].between(23,30) & (mtcars['am'] == 'manual')]

In [ ]:
mtcars[mtcars['gear'].isin([4,5])]
#mtcars['gear'].isin([4,5])
#list cars whose gear is in values 4,5

In [ ]:
mtcars['gear'].isin([4,5])

In [ ]:
mtcars[(mtcars['gear'].isin([4,5])) | (mtcars['am'] == 'auto')]
#all auto or gear = 4,5

In [ ]:
mtcars[~mtcars['gear'].isin([4,5])]
#cars other gear values in 4,5:~opposite

# Select Dtypes

In [ ]:
mtcars.dtypes

In [ ]:
mtcars.select_dtypes(include='number')#.head()
#list coloumns which are numeric

In [ ]:
mtcars.select_dtypes(include='category').head()
#list columns which category type

In [ ]:
mtcars.select_dtypes(include='object').head()

# nlargest for a column

In [ ]:
mtcars.nlargest(5,'mpg')
#list cars which are among top 5 mpg

In [ ]:
mtcars.nsmallest(5,'wt')

# Sort Values

In [ ]:
#mtcars= mtcars.sort_values(by='mpg', ascending=True, inplace=False)
#mtcars.sort_values(by='mpg', ascending=True, inplace=True)

In [54]:
mtcars.sort_values(by='mpg',ascending=True, inplace=True) #.head()
# list mtcars by mpg, in increasing order

In [55]:
mtcars

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1

In [ ]:
mtcars.sort_values(['gear','mpg']).head() #first by gear,mpg

In [ ]:
mtcars.sort_values(['mpg','mpg'],ascending=[False,True]).head()#first by gear, mpg