In [1]:
from sqlalchemy import create_engine,text
import pandas as pd 
import os
import pymysql
import numpy as np

In [2]:
engine1 = create_engine("mysql+pymysql://root:piit2026@localhost:3306/piit")
engine1

Engine(mysql+pymysql://root:***@localhost:3306/piit)

In [3]:
def q(sql, **params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params)

In [4]:
q('show tables')

  Tables_in_piit
0           dept
1            emp
2         munira
3        student
4      studentb2

In [5]:
q("select * from emp")

   empno   ename        job     mgr    hiredate     sal  comm  deptno
0   1234  MUNIRA    MANAGER  7839.0  1982-01-23  5000.0   NaN      10
1   7369   SMITH      CLERK  7902.0  1980-12-17   800.0   NaN      20
2   7788   SCOTT    ANALYST  7566.0  1982-12-09  3000.0   NaN      20
3   7839    KING  PRESIDENT     NaN  1981-11-17  5000.0   NaN      10
4   7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0   0.0      30
5   7876   ADAMS      CLERK  7788.0  1983-01-12  1100.0   NaN      20
6   7900   JAMES      CLERK  7698.0  1981-12-03   950.0   NaN      30
7   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0   NaN      20
8   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0   NaN      10

In [6]:
emp = q("select * from emp")
emp.head()

   empno   ename        job     mgr    hiredate     sal  comm  deptno
0   1234  MUNIRA    MANAGER  7839.0  1982-01-23  5000.0   NaN      10
1   7369   SMITH      CLERK  7902.0  1980-12-17   800.0   NaN      20
2   7788   SCOTT    ANALYST  7566.0  1982-12-09  3000.0   NaN      20
3   7839    KING  PRESIDENT     NaN  1981-11-17  5000.0   NaN      10
4   7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0   0.0      30

In [7]:
q("select * from dept")

    deptno       dname       loc
0     20.0    RESEARCH    DALLAS
1     30.0       SALES   CHICAGO
2     40.0  OPERATIONS    BOSTON
3     10.0  ACCOUNTING  NEW YORK
4     20.0    RESEARCH    DALLAS
5     30.0       SALES   CHICAGO
6     40.0  OPERATIONS    BOSTON
7     10.0  ACCOUNTING  NEW YORK
8     20.0    RESEARCH    DALLAS
9     30.0       SALES   CHICAGO
10    40.0  OPERATIONS    BOSTON

In [8]:
dept = q("select * from dept")
dept.head()

   deptno       dname       loc
0    20.0    RESEARCH    DALLAS
1    30.0       SALES   CHICAGO
2    40.0  OPERATIONS    BOSTON
3    10.0  ACCOUNTING  NEW YORK
4    20.0    RESEARCH    DALLAS

## QUESTION(1): 
### List the names of analysts and salesmen.

In [10]:
# SQL:
q1 = "Select ename From emp where job IN ('ANALYST','SALSEMAN');"
q(q1)

   ename
0  SCOTT
1   FORD

In [11]:
# PYTHON:
emp[['ename','job']][emp['job'].isin(['ANALYST','SALESMAN'])]

    ename       job
2   SCOTT   ANALYST
4  TURNER  SALESMAN
7    FORD   ANALYST

## QUESTION(2):
### List details of employees who have joined before 30 Sep 81.

In [12]:
# SQL:
q2 = "Select * from emp where hiredate <'1981-09-30';"
q(q2)

   empno   ename       job   mgr    hiredate     sal  comm  deptno
0   7369   SMITH     CLERK  7902  1980-12-17   800.0   NaN      20
1   7844  TURNER  SALESMAN  7698  1981-09-08  1500.0   0.0      30

In [13]:
# PYTHON:
emp['hiredate'] = pd.to_datetime(emp['hiredate'])
emp[emp['hiredate'] < '1981-09-30']

   empno   ename       job     mgr   hiredate     sal  comm  deptno
1   7369   SMITH     CLERK  7902.0 1980-12-17   800.0   NaN      20
4   7844  TURNER  SALESMAN  7698.0 1981-09-08  1500.0   0.0      30

In [14]:
emp.head()

   empno   ename        job     mgr   hiredate     sal  comm  deptno
0   1234  MUNIRA    MANAGER  7839.0 1982-01-23  5000.0   NaN      10
1   7369   SMITH      CLERK  7902.0 1980-12-17   800.0   NaN      20
2   7788   SCOTT    ANALYST  7566.0 1982-12-09  3000.0   NaN      20
3   7839    KING  PRESIDENT     NaN 1981-11-17  5000.0   NaN      10
4   7844  TURNER   SALESMAN  7698.0 1981-09-08  1500.0   0.0      30

In [15]:
emp['hiredate'] = pd.to_datetime(emp['hiredate'])

## QUESTION(3):
### List names of employees who are not managers.

In [16]:
# SQL:
# Select ename from emp where job !='MANAGER';
q3 = "Select ename from emp where job <>'MANAGER';"
q(q3)

    ename
0   SMITH
1   SCOTT
2    KING
3  TURNER
4   ADAMS
5   JAMES
6    FORD
7  MILLER

In [17]:
# PYTHON:
emp[emp['job'] !='MANAGER'][['ename']]

    ename
1   SMITH
2   SCOTT
3    KING
4  TURNER
5   ADAMS
6   JAMES
7    FORD
8  MILLER

# QUESTION(4):
### List the names of employees whose employee numbers are 7369, 7521, 7839, 7934, 7788.

In [18]:
# SQL:
q4 = "Select ename from emp where empno IN(7369,7521,7839,7934,7788);"
q(q4)

    ename
0   SMITH
1   SCOTT
2    KING
3  MILLER

In [19]:
# PYTHON:
emp[emp['empno'].isin([7369,7521,7839,7934,7788])][['ename']]

    ename
1   SMITH
2   SCOTT
3    KING
8  MILLER

# QUESTION(5):
### List employees not belonging to department 30, 40, or 10.

In [20]:
# SQL:
q5 = "Select * from emp where deptno Not IN (30,40,10);"
q(q5)

   empno  ename      job   mgr    hiredate     sal  comm  deptno
0   7369  SMITH    CLERK  7902  1980-12-17   800.0  None      20
1   7788  SCOTT  ANALYST  7566  1982-12-09  3000.0  None      20
2   7876  ADAMS    CLERK  7788  1983-01-12  1100.0  None      20
3   7902   FORD  ANALYST  7566  1981-12-03  3000.0  None      20

In [36]:
# PYTHON:
emp[~emp['deptno'].isin([30,40,10])]

   empno  ename      job     mgr   hiredate     sal  comm  deptno
1   7369  SMITH    CLERK  7902.0 1980-12-17   800.0   NaN      20
2   7788  SCOTT  ANALYST  7566.0 1982-12-09  3000.0   NaN      20
5   7876  ADAMS    CLERK  7788.0 1983-01-12  1100.0   NaN      20
7   7902   FORD  ANALYST  7566.0 1981-12-03  3000.0   NaN      20

# QUESTION(6):
### List employee names for those who have joined between 30 June and 31 Dec. ‘81.

In [37]:
# SQL:
q6="Select * from emp where hiredate between '1981-06-30' and '1981-12-31';"
q(q6)

   empno   ename        job     mgr    hiredate     sal  comm  deptno
0   7839    KING  PRESIDENT     NaN  1981-11-17  5000.0   NaN      10
1   7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0   0.0      30
2   7900   JAMES      CLERK  7698.0  1981-12-03   950.0   NaN      30
3   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0   NaN      20

In [38]:
# PYTHON:
emp[(emp['hiredate'] >= '1981-06-30') & (emp['hiredate'] >= '1981-12-31')]['ename']

0    MUNIRA
2     SCOTT
5     ADAMS
8    MILLER
Name: ename, dtype: object

# QUESTION(7):
### List the different designations in the company.

In [39]:
# SQL:
q7= ("select DISTINCT job from emp;")
q(q7)

         job
0    MANAGER
1      CLERK
2    ANALYST
3  PRESIDENT
4   SALESMAN

In [40]:
# PYTHON:
emp['job'].unique()

array(['MANAGER', 'CLERK', 'ANALYST', 'PRESIDENT', 'SALESMAN'],
      dtype=object)

# QUESTION(8):
### List the names of employees who are not eligible for commission.

In [41]:
# SQL:
q8 = ("Select ename from emp where comm IS NULL;")
q(q8)

    ename
0  MUNIRA
1   SMITH
2   SCOTT
3    KING
4   ADAMS
5   JAMES
6    FORD
7  MILLER

In [42]:
# PYTHON:
emp[emp['comm'].isnull()]['ename']

0    MUNIRA
1     SMITH
2     SCOTT
3      KING
5     ADAMS
6     JAMES
7      FORD
8    MILLER
Name: ename, dtype: object

# QUESTION(9):
### List the name and designation of the employee who does not report to anybody.

In [43]:
# SQL:
q9 = ("Select ename,job from emp where mgr IS NULL;")
q(q9)

  ename        job
0  KING  PRESIDENT

In [44]:
# PYTHON:
emp[emp['mgr'].isnull()][['ename', 'job']]

  ename        job
3  KING  PRESIDENT

# QUESTION(10):
### List the employees not assigned to any department.

In [46]:
# SQL:
q10 = ("Select ename from emp where deptno IS NULL;")
q(q10)

Empty DataFrame
Columns: [ename]
Index: []

In [47]:
# PYTHON:
emp[emp['deptno'].isnull()]['ename']

Series([], Name: ename, dtype: object)

# QUESTION(11):
### List the employees who are eligible for commission.

In [54]:
# SQL:
q11 = (" select ename from emp where comm IS NOT NULL;")
q(q11)

    ename
0  TURNER

In [55]:
# PYTHON:
emp[emp['comm'].notnull()]['ename']

4    TURNER
Name: ename, dtype: object

# QUESTION(12):
### List employees whose names either start or end with “S”.

In [53]:
# SQL:
q12= ("Select ename from emp where ename LIKE 'S%' OR ename LIKE  '%S';")
q(q12)

   ename
0  SMITH
1  SCOTT
2  ADAMS
3  JAMES

In [57]:
# PYTHON:
emp[emp['ename'].str.startswith('S') | emp['ename'].str.endswith('S')]['ename']

1    SMITH
2    SCOTT
5    ADAMS
6    JAMES
Name: ename, dtype: object

# QUESTION(13):
### List names of employees whose names have “i” as the second character.

In [62]:
# SQL:
q13 = ("Select ename from emp where ename LIKE '_I%';")
q(q13)

    ename
0    KING
1  MILLER

In [64]:
# PYTHON:
emp[emp['ename'].str[1].str.upper()=='I']['ename']

3      KING
8    MILLER
Name: ename, dtype: object

# QUESTION(14):
### List the number of employees working with the company.

In [65]:
# SQL:
q14 = (" Select COUNT(*) AS total_employees from emp;")
q(q14)

   total_employees
0                9

In [67]:
# PYTHON:
emp.shape[0]

9

# QUESTION(15):
### List the number of designations available in the EMP table.

In [69]:
# SQL:
q15 = ("Select COUNT(DISTINCT job) AS total_designations from emp;")
q(q15)

   total_designations
0                   5

In [72]:
# PYTHON:
emp['job'].nunique()

5

# QUESTION(16):
### List the total salaries paid to the employees.

In [73]:
# SQL:
q16 =("Select SUM(sal) AS total_Salaries from emp;")
q(q16)

   total_Salaries
0         21650.0

In [74]:
# PYTHON:
emp['sal'].sum()

np.float64(21650.0)

# QUESTION(17):
### List the maximum, minimum and average salary in the company.

In [75]:
# SQL:
q17 = ("Select Max(sal) AS maximum_salary,Min(sal) AS minimum_salary, Avg(sal) AS Average_salary from emp;")
q(q17)

   maximum_salary  minimum_salary  Average_salary
0          5000.0           800.0     2405.555556

In [88]:
# PYTHON:
emp['sal'].max()
emp['sal'].min()
emp['sal'].mean()

5000.0

In [81]:
# PYTHON:
emp['sal'].agg(['max','min','mean'])

max     5000.000000
min      800.000000
mean    2405.555556
Name: sal, dtype: float64

# QUESTION(18):
### List the maximum salary paid to a salesman.

In [92]:
# SQL:
q18 = (" select max(sal) AS Max_Salesman_Salary from emp where job = 'SALESMAN';")
q(q18)

   Max_Salesman_Salary
0               1500.0

In [93]:
# PYTHON:
emp[emp['job']=='SALESMAN']['sal'].max()

1500.0