# Missing Values

In [7]:
import pandas as pd
import numpy as np
from pydataset import data

In [34]:
# Create Data
# 4 types of missing values-None,np.nan,pd.NA,NaT
import numpy as np
data = [
    [1,'Taheera', None ,86], 
    [2,'Aelita',56,90],
    [3,'Kulan',np.nan, None ],
    [4,'Batgerel',71,79],
    [5,'Manish', np.nan,78]
]
df = pd.DataFrame(data, columns=['Rollno','Name','Maths','English'])
df

   Rollno      Name  Maths  English
0       1   Taheera    NaN     86.0
1       2    Aelita   56.0     90.0
2       3     Kulan    NaN      NaN
3       4  Batgerel   71.0     79.0
4       5    Manish    NaN     78.0

In [10]:
# How to find missing values from thousands of data
df.isna().sum()

Rollno     0
Name       0
Maths      3
English    1
dtype: int64

In [11]:
df.isna().sum(axis=1)

0    1
1    0
2    2
3    0
4    1
dtype: int64

In [12]:
# How to fill missing values
df.fillna(0)

   Rollno      Name  Maths  English
0       1   Taheera    0.0     86.0
1       2    Aelita   56.0     90.0
2       3     Kulan    0.0      0.0
3       4  Batgerel   71.0     79.0
4       5    Manish    0.0     78.0

In [13]:
df.fillna(40)

   Rollno      Name  Maths  English
0       1   Taheera   40.0     86.0
1       2    Aelita   56.0     90.0
2       3     Kulan   40.0     40.0
3       4  Batgerel   71.0     79.0
4       5    Manish   40.0     78.0

In [14]:
df[df['Rollno']==1]

   Rollno     Name  Maths  English
0       1  Taheera    NaN     86.0

In [16]:
df.loc[df['Rollno']==1,['Maths']]

   Maths
0    NaN

In [17]:
df.loc[df['Rollno']==1,['Maths','English']]

   Maths  English
0    NaN     86.0

In [19]:
df.loc[df['Rollno']==1,['Maths']]=88
df

   Rollno      Name  Maths  English
0       1   Taheera   88.0     86.0
1       2    Aelita   56.0     90.0
2       3     Kulan    NaN      NaN
3       4  Batgerel   71.0     79.0
4       5    Manish    NaN     78.0

In [21]:
df.loc[df['Rollno']==3,['Maths','English']]=[100,100]
df

   Rollno      Name  Maths  English
0       1   Taheera   88.0     86.0
1       2    Aelita   56.0     90.0
2       3     Kulan  100.0    100.0
3       4  Batgerel   71.0     79.0
4       5    Manish    NaN     78.0

In [28]:
df['Maths'].mean()

np.float64(78.75)

In [30]:
df['Maths']=df['Maths'].fillna(df['Maths'].mean())
df

   Rollno      Name   Maths  English
0       1   Taheera   88.00     86.0
1       2    Aelita   56.00     90.0
2       3     Kulan  100.00    100.0
3       4  Batgerel   71.00     79.0
4       5    Manish   78.75     78.0

In [31]:
df['English']=df['English'].fillna(df['English'].min())
df

   Rollno      Name   Maths  English
0       1   Taheera   88.00     86.0
1       2    Aelita   56.00     90.0
2       3     Kulan  100.00    100.0
3       4  Batgerel   71.00     79.0
4       5    Manish   78.75     78.0

In [37]:
data2 = [
    [1,'Taheera', 77], 
    [2,'Aelita',77],
    [3,'Kulan',77],
    [4,'Batgerel',77],
    [5,'Manish',77]
]
df2 = pd.DataFrame(data2, columns=['Rollno','Name','French'])
df2

   Rollno      Name  French
0       1   Taheera      77
1       2    Aelita      77
2       3     Kulan      77
3       4  Batgerel      77
4       5    Manish      77

In [40]:
df3 = pd.merge(df,df2, on=['Rollno','Name'])
df3

   Rollno      Name  Maths  English  French
0       1   Taheera    NaN     86.0      77
1       2    Aelita   56.0     90.0      77
2       3     Kulan    NaN      NaN      77
3       4  Batgerel   71.0     79.0      77
4       5    Manish    NaN     78.0      77