In [1]:
import pandas as pd
import numpy as np
from pydataset import data
mtcars = data('mtcars')
mtcars.shape

(32, 11)

# Pivot Table

- Index= what goes down the rows
- columns= → What goes across the top
- values= → What fills the table
- aggfunc= → How to summarize if there are duplicates

In [2]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [3]:
#how many cars have gear=5, am=0

In [4]:
mtcars.pivot_table(values ='mpg', index='gear', observed=False)
#no aggregation or defalt aggregation is mean
#mean mpg of gear3 car is 16

            mpg
gear
3     16.106667
4     24.533333
5     21.380000

In [5]:
#?mtcars.pivot_table

In [6]:
mtcars.pivot_table(values='hp',index='cyl',observed=False)
#mean hp of cyl 4 car is 82

             hp
cyl
4     82.636364
6    122.285714
8    209.214286

In [7]:
mtcars.pivot_table(values='mpg',index=['gear','am'],observed=False,aggfunc=['sum','mean'])

           sum       mean
           mpg        mpg
gear am
3    0   241.6  16.106667
4    0    84.2  21.050000
     1   210.2  26.275000
5    1   106.9  21.380000

In [8]:
mtcars.pivot_table(values=['mpg','hp'],index=['gear','am'],observed=False,aggfunc=['sum','mean','count']).reset_index()
#sum of mpg for each gear type

  gear am   sum               mean            count
             hp    mpg          hp        mpg    hp mpg
0    3  0  2642  241.6  176.133333  16.106667    15  15
1    4  0   403   84.2  100.750000  21.050000     4   4
2    4  1   671  210.2   83.875000  26.275000     8   8
3    5  1   978  106.9  195.600000  21.380000     5   5

In [9]:
mtcars.pivot_table(values=['mpg','hp'],index=['gear','am'],observed=True,aggfunc=['sum','mean','count']).reset_index()

  gear am   sum               mean            count
             hp    mpg          hp        mpg    hp mpg
0    3  0  2642  241.6  176.133333  16.106667    15  15
1    4  0   403   84.2  100.750000  21.050000     4   4
2    4  1   671  210.2   83.875000  26.275000     8   8
3    5  1   978  106.9  195.600000  21.380000     5   5

In [10]:
pd.pivot_table( data=mtcars,observed=False,
    index='gear',       #Rows
    values='mpg',        #Values to summerise
    aggfunc='median',    #Aggregation function
)
#median of gear 3 car is 15

       mpg
gear
3     15.5
4     22.8
5     19.7

In [11]:
pivot1 = pd.pivot_table(
    data=mtcars,observed=False,
    index='gear',    #Rows
    columns='am',   #Coloumns
    values='mpg',    #Values to summerise
    aggfunc='mean',  #Aggregation function
)

In [12]:
pivot1
# Mean of gear-3 & auto TX -16 while for gear-3 & manual TX- no cars

am            0       1
gear
3     16.106667     NaN
4     21.050000  26.275
5           NaN  21.380

In [13]:
print(mtcars.am.value_counts(),mtcars.cyl.value_counts())

am
0    19
1    13
Name: count, dtype: int64 cyl
8    14
4    11
6     7
Name: count, dtype: int64

In [14]:
pd.pivot_table(observed=False, data=mtcars, index='gear', columns='am', values='mpg', aggfunc=['mean','max','min','count','sum']).reset_index()
# 32Cars

   gear       mean           max         min       count         sum
am               0       1     0     1     0     1     0    1      0      1
0     3  16.106667     NaN  21.5   NaN  10.4   NaN  15.0  NaN  241.6    NaN
1     4  21.050000  26.275  24.4  33.9  17.8  21.0   4.0  8.0   84.2  210.2
2     5        NaN  21.380   NaN  30.4   NaN  15.0   NaN  5.0    NaN  106.9

In [15]:
pd.pivot_table(data=mtcars, index=['gear','am'], columns='cyl', values='mpg', aggfunc=['mean','max','min','count','sum','std']).reset_index()
#19.75 mean mpg gear-3,am0,cyl6

    gear am       mean                 max               min              \
cyl                  4      6      8     4     6     8     4     6     8
0      3  0  21.500000  19.75  15.05  21.5  21.4  19.2  21.5  18.1  10.4
1      4  0  23.600000  18.50    NaN  24.4  19.2   NaN  22.8  17.8   NaN
2      4  1  28.033333  21.00    NaN  33.9  21.0   NaN  21.4  21.0   NaN
3      5  1  28.200000  19.70  15.40  30.4  19.7  15.8  26.0  19.7  15.0

    count               sum                    std
cyl     4    6     8      4     6      8         4         6         8
0     1.0  2.0  12.0   21.5  39.5  180.6       NaN  2.333452  2.774396
1     2.0  2.0   NaN   47.2  37.0    NaN  1.131371  0.989949       NaN
2     6.0  2.0   NaN  168.2  42.0    NaN  5.118854  0.000000       NaN
3     2.0  1.0   2.0   56.4  19.7   30.8  3.111270       NaN  0.565685

# Advanced-2

- wide,long
- missing values
- airquality dataset is perfect
- wide formate: columns for ozone,solar.R,wind,temp,day,month
- Has missing values ozone and solar.R - great for isnull(),fillna(),dropna() practice
- can be melted into long formate to have 'variables' and 'value 'columns

In [21]:
from pydataset import data
import pandas as pd
aq = data('airquality')
aq.head()

   Ozone  Solar.R  Wind  Temp  Month  Day
1   41.0    190.0   7.4    67      5    1
2   36.0    118.0   8.0    72      5    2
3   12.0    149.0  12.6    74      5    3
4   18.0    313.0  11.5    62      5    4
5    NaN      NaN  14.3    56      5    5

In [17]:
#Roll no Name  Maths English
1 Taheera  70  86
2 Aelita   56 90
3 Kulan 87  90
4 Batgerel 71 79
5 Manisha 88,78

SyntaxError: invalid syntax (4195180485.py, line 2)

In [35]:
data = [
    [1,'Taheera', 70,86], 
    [2,'Aelita',56,90],
    [3,'Kulan',87,90],
    [4,'Batgerel',71,79],
    [5,'Manish', 88,78]
]
df = pd.DataFrame(data, columns=['Rollno','Name','Maths','English'])

In [36]:
df

   Rollno      Name  Maths  English
0       1   Taheera     70       86
1       2    Aelita     56       90
2       3     Kulan     87       90
3       4  Batgerel     71       79
4       5    Manish     88       78

In [ ]:
data = [
    ['Alice', 25,'New York'], 
    ['Bob',30,'London'],
    ['Charlie',35,'Paris']
]
df = pd.DataFrame(data, columns=['Name','Age','City'])

In [ ]:
df

In [ ]:
data = {'Name': ['Alice', 'Bob','Charlie'], 'Age': [25, 30,35],'City':['New York', 'London', 'Paris']}

df = pd.DataFrame(data)

In [ ]:
df

In [ ]:
data = [{'Name': 'Alice', 'Age': 25}, {'Name': 'Bob', 'Age': 30}]
df = pd.DataFrame(data)

In [ ]:
df

In [ ]:
### wide to long
# roll,name,subject,marks

In [32]:
df =  pd.DataFrame(data)

In [48]:
df_long = df.melt(id_vars=['Rollno','Name'],
                  value_vars=['Maths','English'],
                  var_name='Subject',
                  value_name='Marks')
df_long

   Rollno      Name  Subject  Marks
0       1   Taheera    Maths     70
1       2    Aelita    Maths     56
2       3     Kulan    Maths     87
3       4  Batgerel    Maths     71
4       5    Manish    Maths     88
5       1   Taheera  English     86
6       2    Aelita  English     90
7       3     Kulan  English     90
8       4  Batgerel  English     79
9       5    Manish  English     78

In [28]:
long_df = df.melt(id_vars=['Rollno','Name'],
                  value_vars=['Maths','English'],
                  var_name='Subject',
                  value_name='Marks')
long_df

   Rollno      Name  Subject  Marks
0       1   Taheera    Maths     70
1       2    Aelita    Maths     56
2       3     Kulan    Maths     87
3       4  Batgerel    Maths     71
4       5    Manish    Maths     88
5       1   Taheera  English     86
6       2    Aelita  English     90
7       3     Kulan  English     90
8       4  Batgerel  English     79
9       5    Manish  English     78

In [38]:
wide_df = df_long.pivot(index=['Rollno','Name'],columns='Subject',values='Marks').reset_index()
wide_df

Subject  Rollno      Name  English  Maths
0             1   Taheera       86     70
1             2    Aelita       90     56
2             3     Kulan       90     87
3             4  Batgerel       79     71
4             5    Manish       78     88

In [39]:
wide_df = df_long.pivot(index=['Rollno','Name'],columns='Subject',values='Marks')
wide_df

Subject          English  Maths
Rollno Name
1      Taheera        86     70
2      Aelita         90     56
3      Kulan          90     87
4      Batgerel       79     71
5      Manish         78     88

In [45]:
wide_df = df_long.pivot(index=['Rollno','Name'],columns='Subject',values='Marks').reset_index(drop=False).rename_axis(None,axis=1)
wide_df

   Rollno      Name  English  Maths
0       1   Taheera       86     70
1       2    Aelita       90     56
2       3     Kulan       90     87
3       4  Batgerel       79     71
4       5    Manish       78     88

In [46]:
wide_df2 = df_long.pivot_table(index=['Rollno','Name'],columns='Subject',values='Marks',aggfunc='sum').reset_index(drop=False).rename_axis(None,axis=1)
wide_df2

   Rollno      Name  English  Maths
0       1   Taheera       86     70
1       2    Aelita       90     56
2       3     Kulan       90     87
3       4  Batgerel       79     71
4       5    Manish       78     88

In [51]:
df_long.groupby('Subject')['Marks'].agg(['sum','mean','count'])

         sum  mean  count
Subject
English  423  84.6      5
Maths    372  74.4      5

In [54]:
df.groupby('Name').mean()

          Rollno  Maths  English
Name
Aelita       2.0   56.0     90.0
Batgerel     4.0   71.0     79.0
Kulan        3.0   87.0     90.0
Manish       5.0   88.0     78.0
Taheera      1.0   70.0     86.0

In [57]:
df[['Maths','English']].mean()

Maths      74.4
English    84.6
dtype: float64

In [65]:
df[['Maths','English']].mean().reset_index()

     index     0
0    Maths  74.4
1  English  84.6

In [68]:
df.dtypes

Rollno      int64
Name       object
Maths       int64
English     int64
dtype: object

In [72]:
df.select_dtypes(include='number').mean()

Rollno      3.0
Maths      74.4
English    84.6
dtype: float64