In [1]:
#SQL - Python Connect

In [12]:
!pip install sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in c:\analytics\setup\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\analytics\setup\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\analytics\setup\lib\site-packages (from sqlalchemy) (4.15.0)

In [13]:
pip install pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in c:\users\owner\appdata\roaming\python\python313\site-packages (1.1.3)
Note: you may need to restart the kernel to use updated packages.

In [11]:
# libraries (install if required)
from sqlalchemy import create_engine, text
import pymysql
import pandas as pd
import os

In [9]:
# URL-encode special chars in password if any (e.g., # -> %23, @ -> %40)  #Pass@123 - Pass%40123
engine1 = create_engine("mysql+pymysql://root:piit2026@localhost:3306/piit")
print(engine1)
#setting up connection mysql with user name - piuser, pwd - Pass@123 and to database piit at port no  3306

Engine(mysql+pymysql://root:***@localhost:3306/piit)

In [8]:
engine1 = create_engine("mysql+pymysql://root:piit2026@localhost:3306/piit")
print(engine1)

Engine(mysql+pymysql://root:***@localhost:3306/piit)

In [15]:
# function to run the query with parameters or query
def q(sql, **params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params)

In [16]:
q("SELECT * FROM student")

,id,name,branch,score,exam_date,remarks
0,1,Rick Johnson,Mechanical,63.68,2025-03-30,Average
1,2,Shannon Hall,Electrical,74.35,2024-03-28,Outstanding
2,3,Stephanie Flores,Computer Science,88.97,2024-05-17,Average
3,4,Keith Ferrell,Civil,75,2025-06-22,Average
4,5,Corey Allen,Computer Science,63.14,2025-05-17,Needs Improvement
5,6,Brittney Galloway,Computer Science,51.85,2025-02-01,Needs Improvement
6,7,Kathryn Gordon,Electrical,70.88,2023-12-10,Outstanding
7,8,Julia Warren,Electrical,63.07,2023-11-21,Needs Improvement
8,9,Carol Cunningham,Computer Science,87.88,2024-07-29,Good
9,10,Cassidy Crawford,Civil,52.46,2025-02-25,Excellent
10,11,William Sanders,Electronics,53.81,2024-01-02,Average
11,12,Amanda Chapman,Mechanical,58.49,2025-03-04,Outstanding
12,13,Amanda Reese,Electronics,54.26,2023-10-15,Average
13,14,Katherine Morrow,Civil,85.95,2023-09-23,Outstanding
14,15,Daniel Graham,Computer Science,65,2024-10-27,Needs Improvement
15,16,Alexander Rivers,Electrical,93.69,2024-11-09,Excellent
16,17,Sarah Gordon,Computer Science,86.08,2023-11-24,Excellent
17,18,Lauren Weaver,Electronics,50.65,2025-01-18,Good
18,19,Kim Herrera,Electronics,54.02,2025-01-18,Average
19,20,Rhonda Sullivan,Civil,88.3,2024-02-04,Outstanding
20,21,Sara Gomez,Electronics,64.88,2024-12-01,Needs Improvement
21,22,Emily Moore,Civil,65.21,2024-03-15,Outstanding
22,23,Robert Delacruz,Civil,51.92,2024-02-15,Good
23,24,Shawn Simon,Computer Science,94.68,2023-12-22,Average
24,25,Danielle Le,Mechanical,91.5,2024-02-28,Outstanding
25,26,Alexandra Alexander,Electronics,55.09,2025-04-13,Outstanding
26,27,Anna Zimmerman,Civil,83.72,2024-10-28,Average
27,28,Michael Johnson,Electronics,78.04,2024-07-05,Average
28,29,Michael Higgins DDS,Computer Science,90.45,2025-02-20,Outstanding
29,30,Jodi Chapman,Electronics,54.13,2025-07-04,Needs Improvement
30,1,Rick Johnson,Mechanical,63.68,2025-03-30,Average
31,2,Shannon Hall,Electrical,74.35,2024-03-28,Outstanding
32,3,Stephanie Flores,Computer Science,88.97,2024-05-17,Average
33,4,Keith Ferrell,Civil,75,2025-06-22,Average
34,5,Corey Allen,Computer Science,63.14,2025-05-17,Needs Improvement
35,6,Brittney Galloway,Computer Science,51.85,2025-02-01,Needs Improvement
36,7,Kathryn Gordon,Electrical,70.88,2023-12-10,Outstanding
37,8,Julia Warren,Electrical,63.07,2023-11-21,Needs Improvement
38,9,Carol Cunningham,Computer Science,87.88,2024-07-29,Good
39,10,Cassidy Crawford,Civil,52.46,2025-02-25,Excellent
40,11,William Sanders,Electronics,53.81,2024-01-02,Average
41,12,Amanda Chapman,Mechanical,58.49,2025-03-04,Outstanding
42,13,Amanda Reese,Electronics,54.26,2023-10-15,Average
43,14,Katherine Morrow,Civil,85.95,2023-09-23,Outstanding
44,15,Daniel Graham,Computer Science,65,2024-10-27,Needs Improvement
45,16,Alexander Rivers,Electrical,93.69,2024-11-09,Excellent
46,17,Sarah Gordon,Computer Science,86.08,2023-11-24,Excellent
47,18,Lauren Weaver,Electronics,50.65,2025-01-18,Good
48,19,Kim Herrera,Electronics,54.02,2025-01-18,Average
49,20,Rhonda Sullivan,Civil,88.3,2024-02-04,Outstanding
50,21,Sara Gomez,Electronics,64.88,2024-12-01,Needs Improvement
51,22,Emily Moore,Civil,65.21,2024-03-15,Outstanding
52,23,Robert Delacruz,Civil,51.92,2024-02-15,Good
53,24,Shawn Simon,Computer Science,94.68,2023-12-22,Average
54,25,Danielle Le,Mechanical,91.5,2024-02-28,Outstanding
55,26,Alexandra Alexander,Electronics,55.09,2025-04-13,Outstanding
56,27,Anna Zimmerman,Civil,83.72,2024-10-28,Average
57,28,Michael Johnson,Electronics,78.04,2024-07-05,Average
58,29,Michael Higgins DDS,Computer Science,90.45,2025-02-20,Outstanding
59,30,Jodi Chapman,Electronics,54.13,2025-07-04,Needs Improvement

select * from student;
 select * from student where branch = "Civil";
 select * from student where branch in ('Civil','Mechanical');
 select * from student where name like 'R%';
 select sum(score) from student;
select max(score) from student;
select min(score) from student;
select avg(score) from student;
select branch, avg(score) as avgscore from student group by branch;
select branch, avg(score) as avgscore, count(*) from student group by branch;
select * from student order by score desc;

In [17]:
q("SELECT * FROM student where branch ='Civil';")

    id              name branch  score   exam_date      remarks
0    4     Keith Ferrell  Civil     75  2025-06-22      Average
1   10  Cassidy Crawford  Civil  52.46  2025-02-25    Excellent
2   14  Katherine Morrow  Civil  85.95  2023-09-23  Outstanding
3   20   Rhonda Sullivan  Civil   88.3  2024-02-04  Outstanding
4   22       Emily Moore  Civil  65.21  2024-03-15  Outstanding
5   23   Robert Delacruz  Civil  51.92  2024-02-15         Good
6   27    Anna Zimmerman  Civil  83.72  2024-10-28      Average
7    4     Keith Ferrell  Civil     75  2025-06-22      Average
8   10  Cassidy Crawford  Civil  52.46  2025-02-25    Excellent
9   14  Katherine Morrow  Civil  85.95  2023-09-23  Outstanding
10  20   Rhonda Sullivan  Civil   88.3  2024-02-04  Outstanding
11  22       Emily Moore  Civil  65.21  2024-03-15  Outstanding
12  23   Robert Delacruz  Civil  51.92  2024-02-15         Good
13  27    Anna Zimmerman  Civil  83.72  2024-10-28      Average

In [18]:
q("select * from student where branch in ('Civil','Mechanical');")

    id              name      branch  score   exam_date      remarks
0    1      Rick Johnson  Mechanical  63.68  2025-03-30      Average
1    4     Keith Ferrell       Civil     75  2025-06-22      Average
2   10  Cassidy Crawford       Civil  52.46  2025-02-25    Excellent
3   12    Amanda Chapman  Mechanical  58.49  2025-03-04  Outstanding
4   14  Katherine Morrow       Civil  85.95  2023-09-23  Outstanding
5   20   Rhonda Sullivan       Civil   88.3  2024-02-04  Outstanding
6   22       Emily Moore       Civil  65.21  2024-03-15  Outstanding
7   23   Robert Delacruz       Civil  51.92  2024-02-15         Good
8   25       Danielle Le  Mechanical   91.5  2024-02-28  Outstanding
9   27    Anna Zimmerman       Civil  83.72  2024-10-28      Average
10   1      Rick Johnson  Mechanical  63.68  2025-03-30      Average
11   4     Keith Ferrell       Civil     75  2025-06-22      Average
12  10  Cassidy Crawford       Civil  52.46  2025-02-25    Excellent
13  12    Amanda Chapman  Mechanical  58.49  2025-03-04  Outstanding
14  14  Katherine Morrow       Civil  85.95  2023-09-23  Outstanding
15  20   Rhonda Sullivan       Civil   88.3  2024-02-04  Outstanding
16  22       Emily Moore       Civil  65.21  2024-03-15  Outstanding
17  23   Robert Delacruz       Civil  51.92  2024-02-15         Good
18  25       Danielle Le  Mechanical   91.5  2024-02-28  Outstanding
19  27    Anna Zimmerman       Civil  83.72  2024-10-28      Average

In [26]:
import pandas as pd

In [20]:
df2= pd.read_sql("select * from student", engine1)
df2.shape
df2

,id,name,branch,score,exam_date,remarks
0,1,Rick Johnson,Mechanical,63.68,2025-03-30,Average
1,2,Shannon Hall,Electrical,74.35,2024-03-28,Outstanding
2,3,Stephanie Flores,Computer Science,88.97,2024-05-17,Average
3,4,Keith Ferrell,Civil,75,2025-06-22,Average
4,5,Corey Allen,Computer Science,63.14,2025-05-17,Needs Improvement
5,6,Brittney Galloway,Computer Science,51.85,2025-02-01,Needs Improvement
6,7,Kathryn Gordon,Electrical,70.88,2023-12-10,Outstanding
7,8,Julia Warren,Electrical,63.07,2023-11-21,Needs Improvement
8,9,Carol Cunningham,Computer Science,87.88,2024-07-29,Good
9,10,Cassidy Crawford,Civil,52.46,2025-02-25,Excellent
10,11,William Sanders,Electronics,53.81,2024-01-02,Average
11,12,Amanda Chapman,Mechanical,58.49,2025-03-04,Outstanding
12,13,Amanda Reese,Electronics,54.26,2023-10-15,Average
13,14,Katherine Morrow,Civil,85.95,2023-09-23,Outstanding
14,15,Daniel Graham,Computer Science,65,2024-10-27,Needs Improvement
15,16,Alexander Rivers,Electrical,93.69,2024-11-09,Excellent
16,17,Sarah Gordon,Computer Science,86.08,2023-11-24,Excellent
17,18,Lauren Weaver,Electronics,50.65,2025-01-18,Good
18,19,Kim Herrera,Electronics,54.02,2025-01-18,Average
19,20,Rhonda Sullivan,Civil,88.3,2024-02-04,Outstanding
20,21,Sara Gomez,Electronics,64.88,2024-12-01,Needs Improvement
21,22,Emily Moore,Civil,65.21,2024-03-15,Outstanding
22,23,Robert Delacruz,Civil,51.92,2024-02-15,Good
23,24,Shawn Simon,Computer Science,94.68,2023-12-22,Average
24,25,Danielle Le,Mechanical,91.5,2024-02-28,Outstanding
25,26,Alexandra Alexander,Electronics,55.09,2025-04-13,Outstanding
26,27,Anna Zimmerman,Civil,83.72,2024-10-28,Average
27,28,Michael Johnson,Electronics,78.04,2024-07-05,Average
28,29,Michael Higgins DDS,Computer Science,90.45,2025-02-20,Outstanding
29,30,Jodi Chapman,Electronics,54.13,2025-07-04,Needs Improvement
30,1,Rick Johnson,Mechanical,63.68,2025-03-30,Average
31,2,Shannon Hall,Electrical,74.35,2024-03-28,Outstanding
32,3,Stephanie Flores,Computer Science,88.97,2024-05-17,Average
33,4,Keith Ferrell,Civil,75,2025-06-22,Average
34,5,Corey Allen,Computer Science,63.14,2025-05-17,Needs Improvement
35,6,Brittney Galloway,Computer Science,51.85,2025-02-01,Needs Improvement
36,7,Kathryn Gordon,Electrical,70.88,2023-12-10,Outstanding
37,8,Julia Warren,Electrical,63.07,2023-11-21,Needs Improvement
38,9,Carol Cunningham,Computer Science,87.88,2024-07-29,Good
39,10,Cassidy Crawford,Civil,52.46,2025-02-25,Excellent
40,11,William Sanders,Electronics,53.81,2024-01-02,Average
41,12,Amanda Chapman,Mechanical,58.49,2025-03-04,Outstanding
42,13,Amanda Reese,Electronics,54.26,2023-10-15,Average
43,14,Katherine Morrow,Civil,85.95,2023-09-23,Outstanding
44,15,Daniel Graham,Computer Science,65,2024-10-27,Needs Improvement
45,16,Alexander Rivers,Electrical,93.69,2024-11-09,Excellent
46,17,Sarah Gordon,Computer Science,86.08,2023-11-24,Excellent
47,18,Lauren Weaver,Electronics,50.65,2025-01-18,Good
48,19,Kim Herrera,Electronics,54.02,2025-01-18,Average
49,20,Rhonda Sullivan,Civil,88.3,2024-02-04,Outstanding
50,21,Sara Gomez,Electronics,64.88,2024-12-01,Needs Improvement
51,22,Emily Moore,Civil,65.21,2024-03-15,Outstanding
52,23,Robert Delacruz,Civil,51.92,2024-02-15,Good
53,24,Shawn Simon,Computer Science,94.68,2023-12-22,Average
54,25,Danielle Le,Mechanical,91.5,2024-02-28,Outstanding
55,26,Alexandra Alexander,Electronics,55.09,2025-04-13,Outstanding
56,27,Anna Zimmerman,Civil,83.72,2024-10-28,Average
57,28,Michael Johnson,Electronics,78.04,2024-07-05,Average
58,29,Michael Higgins DDS,Computer Science,90.45,2025-02-20,Outstanding
59,30,Jodi Chapman,Electronics,54.13,2025-07-04,Needs Improvement

In [27]:
df2['score'].dtype

dtype('O')

In [29]:
df2['score']=pd.to_numeric(df2['score'],errors='coerce')

In [30]:
df2.groupby('branch')['score'].mean()

branch
Civil               71.794286
Computer Science    78.506250
Electrical          75.497500
Electronics         58.110000
Mechanical          71.223333
Name: score, dtype: float64

In [31]:
df2.groupby('remarks')['score'].mean()

remarks
Average              71.797778
Excellent            77.410000
Good                 63.483333
Needs Improvement    60.345000
Outstanding          75.580000
Name: score, dtype: float64

In [32]:
df2.groupby(['branch','remarks'])['score'].mean()

branch            remarks
Civil             Average              79.360000
                  Excellent            52.460000
                  Good                 51.920000
                  Outstanding          79.820000
Computer Science  Average              91.825000
                  Excellent            86.080000
                  Good                 87.880000
                  Needs Improvement    59.996667
                  Outstanding          90.450000
Electrical        Excellent            93.690000
                  Needs Improvement    63.070000
                  Outstanding          72.615000
Electronics       Average              60.032500
                  Good                 50.650000
                  Needs Improvement    59.505000
                  Outstanding          55.090000
Mechanical        Average              63.680000
                  Outstanding          74.995000
Name: score, dtype: float64

In [34]:
df2.groupby(['branch','remarks'])['score'].agg(['mean','min','max'])

                                         mean    min    max
branch           remarks
Civil            Average            79.360000  75.00  83.72
                 Excellent          52.460000  52.46  52.46
                 Good               51.920000  51.92  51.92
                 Outstanding        79.820000  65.21  88.30
Computer Science Average            91.825000  88.97  94.68
                 Excellent          86.080000  86.08  86.08
                 Good               87.880000  87.88  87.88
                 Needs Improvement  59.996667  51.85  65.00
                 Outstanding        90.450000  90.45  90.45
Electrical       Excellent          93.690000  93.69  93.69
                 Needs Improvement  63.070000  63.07  63.07
                 Outstanding        72.615000  70.88  74.35
Electronics      Average            60.032500  53.81  78.04
                 Good               50.650000  50.65  50.65
                 Needs Improvement  59.505000  54.13  64.88
                 Outstanding        55.090000  55.09  55.09
Mechanical       Average            63.680000  63.68  63.68
                 Outstanding        74.995000  58.49  91.50