# Strings in Python
### a sequence of characters used to represent text
### immutatable
### name = 'Dhiraj' -> 'DHraj'

In [2]:
string1='Diraj'
print(string1)

Diraj

In [5]:
print(string1[0])

U

In [4]:
print(string1[0])
#string1[0]='N'
string1 ='Upadhyaya'
print(string1)

U
Upadhyaya

In [3]:
# Creating  Strings
print("1. Creating Strings")
s1 = "Hello"  #double quote
s2 = 'World'  #single quote
s3 = """This is a multiline 
       String"""  #triple quote (single or double)
print(s1)
print(s2)
print(s3)

1. Creating Strings
Hello
World
This is a multiline
       String

In [4]:
print("1. Creating String")
s1 = "Hello"
s2 = 'world'
s3 = """This is a multiline (my name is munira akhtar)
       Strings"""
print(s1)
print(s2)
print(s3)

1. Creating String
Hello
world
This is a multiline (my name is munira akhtar)
       Strings

In [5]:
ms = '''In Python, a string is a sequence of characters used to represent text 
GeeksforGeeks
GeeksforGeeks
 +1
. Strings are one of the most fundamental and frequently used data types in the language'''
print(ms)

In Python, a string is a sequence of characters used to represent text
GeeksforGeeks
GeeksforGeeks
 +1
. Strings are one of the most fundamental and frequently used data types in the language

In [6]:
 # 2. String Concatenation
print("\n2. Concatenation")
full = s1 + " " + s2
print("Concatenated:", full)

2. Concatenation
Concatenated: Hello world

In [7]:
sc ='Aelita' + '....' + "Khulan"
print(sc)

Aelita....Khulan

In [10]:
# 3. String Repetition 
print("\n3. Repetition") #\n3 means next line character
repeat = "Hi . How are you? " * 5
print(repeat, end =' I have reached end of string')

3. Repetition
Hi . How are you? Hi . How are you? Hi . How are you? Hi . How are you? Hi . How are you?  I have reached end of string

In [ ]:
#In Python, \n stands for the newline character
#It is an escape sequence used to insert a line break within a string

In [11]:
print("\t\t3. Repetition") #\t3 means next line tab
repeat = "Hi .  How are you! " * 5
print(repeat, end=' : I have reached end of string')

		3. Repetition
Hi .  How are you! Hi .  How are you! Hi .  How are you! Hi .  How are you! Hi .  How are you!  : I have reached end of string

In [23]:
print("\n\n\t\t3. Repetition")
repeat = "Hi .  How are you! " * 5
print(repeat, end=' : I have reached end of string')

		3. Repetition
Hi .  How are you! Hi .  How are you! Hi .  How are you! Hi .  How are you! Hi .  How are you!  : I have reached end of string

In [27]:
# 4. Indexing (Access characters)
print('\n')
print("4. Indexing")
text = "PythonA"
print(' The string is ', text)
print("Frist character:", text[0])
print("Last character:", text[-1])
print("3rd character:", text[2])

4. Indexing
 The string is  PythonA
Frist character: P
Last character: A
3rd character: t

In [28]:
len(text)

7

In [30]:
len(text)/2

3.5

In [31]:
round(len(text)/2)

4

In [33]:
print("Maiden character:", text[round(len(text)/2)])

Maiden character: o

In [34]:
print("Maiden character:", text[round(len(text)/2)-1])

Maiden character: h

In [35]:
# Reverse string order in python
print('Actual string', text, 'Reverse string is', text[:2:-1])

Actual string PythonA Reverse string is Anoh

In [36]:
print('Actual string', text, 'Reverse string is', text[::-1])

Actual string PythonA Reverse string is AnohtyP

In [37]:
text[::-1]

'AnohtyP'

In [39]:
# 5. Slicing (Get part of string)
# string[start:stop:step]
print("\n5. Slicing")
print("First 3 chars:", text[0:3])
print("From index 2:", text[2:])
print("Reverse string:", text[::-1])

5. Slicing
First 3 chars: Pyt
From index 2: thonA
Reverse string: AnohtyP

In [41]:
# 6. Strings Methods
print("\n6 String Methods")
name = "data science"
print("Original String with spaces-",name)
print("Upper:",name.upper())
print("Lower:",name.lower())
print("Strip spaces:",name.strip())
print("title case:",name.title())
print("Replace:",name.replace("science","analysis"))

6 String Methods
Original String with spaces- data science
Upper: DATA SCIENCE
Lower: data science
Strip spaces: data science
title case: Data Science
Replace: data analysis

In [ ]:
# 7. Checking Content
# -------------------------------
print("\n7. Checking Content")
sample = "Python123"
print("Is alphabet:", sample.isalpha())
print("Is digit:", sample.isdigit())
print("Is alphanumeric:", sample.isalnum())

In [42]:
# 7. Checking Content
print("\n7. Checking Content")
sample= "Python123"
print("Is alphabet:",sample.isalpha())
print("Is digit:",sample.isdigit())
print("Is alphanumeric:",sample.isalnum())

7. Checking Content
Is alphabet: False
Is digit: False
Is alphanumeric: True

In [43]:
print("\n7. Checking Content")
sample= "123"
print("Is alphabet:",sample.isalpha())
print("Is digit:",sample.isdigit())
print("Is alphanumeric:",sample.isalnum())

7. Checking Content
Is alphabet: False
Is digit: True
Is alphanumeric: True

In [46]:
# 8. Splitting and Joining
print("\n8. Split & Join")
sentence = "Python is easy to learn"
print(' the Sentence is ', sentence)
word = sentence.split(" ")
print("Split:", word)
joined = "-".join(word)
print("joined:",joined)

8. Split & Join
 the Sentence is  Python is easy to learn
Split: ['Python', 'is', 'easy', 'to', 'learn']
joined: Python-is-easy-to-learn

In [ ]:
# 9. String Formatting
# -------------------------------
print("\n9. Formatting")
name = "Taheera"
age = 25
gender ='F'
city ='New York'
# Old style
print("My name is %s and I am %d years old, and my gender is %s" % (name, age,gender))
# format()
print("My name is {} and I am {} years old, with gender is {} and city in {}".format(name, age, gender, city))
# f-string (recommended)
print(f"My gender is {gender}, name is {name} and I am {age} years old")

In [49]:
# 9. String Formatting
print("\n9. Formating")
name = "Munira"
age = 25
gender = 'F'
city = 'Virginia'
# Old style
print("My name is %s and I am %d years old, and my gender is %s" % (name,age,gender))
# Format()
print("My name is {} and I am {} years old, and my gender is {} and city in {}".format(name,age,gender,city))
# F-string(recommended)
print(f"My gender is{gender},name is {name} and I am {age} years old")

9. Formating
My name is Munira and I am 25 years old, and my gender is F
My name is Munira and I am 25 years old, and my gender is F and city in Virginia
My gender isF,name is Munira and I am 25 years old

In [54]:
# 11. Important Concept: Strings are Immutable
print("n11. Immutability")
text = "hello"
# text[0] = 'H'  # ❌ This will give an error
# Correct way:
text = "H" + text[1:]
print("Modified string:",text)
print("He said \"Python is fun\"")

n11. Immutability
Modified string: Hello
He said "Python is fun"

In [56]:
# 12. Length of String
print("\n12. Length")
print("Length of Python':",len("Python"))

12. Length
Length of Python': 6

In [57]:
# 13. Membership (in keyword)
print("\n13. Membership")
print("Py" in "Python")
print("Java" not in "Python")

13. Membership
True
True

# More

In [2]:
import pandas as pd
from pydataset import data

In [3]:
# Create mtcars dataset with car names
data = {
    "car_name": [ "Mazda RX4", "Mazda RX4    Wag", "Datsun 710","Hornet 4 Drive", "Hornet   Sportabout  ", "Valiant", "Duster 360", "merc 240D", "Merc 230", "Merc 280" ],
    "mpg": [21.0, 21.0, 22.8, 21.4, 18.7, 18.1, 14.3, 24.4, 22.8, 19.2]}
df = pd.DataFrame(data)
print("Original Data:\n", df)

Original Data:
                 car_name   mpg
0              Mazda RX4  21.0
1       Mazda RX4    Wag  21.0
2             Datsun 710  22.8
3         Hornet 4 Drive  21.4
4  Hornet   Sportabout    18.7
5                Valiant  18.1
6             Duster 360  14.3
7              merc 240D  24.4
8               Merc 230  22.8
9               Merc 280  19.2

In [4]:
# Search
mazda_cars = df[df['car_name'].str.contains("Mazda")]
print("n\Cars with Mazda':\n",mazda_cars)
# .str.contains() → pattern search
# Case sensitive by default

n\Cars with Mazda':
            car_name   mpg
0         Mazda RX4  21.0
1  Mazda RX4    Wag  21.0

In [5]:
df[df['car_name'].str.contains("Merc", case=True)]

   car_name   mpg
8  Merc 230  22.8
9  Merc 280  19.2

In [6]:
df[df['car_name'].str.contains("merc", case=False)]
# case insenstive

    car_name   mpg
7  merc 240D  24.4
8   Merc 230  22.8
9   Merc 280  19.2

In [9]:
# FILTER (Start / End patterns
# Cars starting with “Merc”
merc_cars = df[df['car_name'].str.startswith("Merc")]
print("\nCars starting with 'Merc':\n",merc_cars)

Cars starting with 'Merc':
    car_name   mpg
8  Merc 230  22.8
9  Merc 280  19.2

In [10]:
df[df['car_name'].str.startswith(("Merc",'merc'))]

    car_name   mpg
7  merc 240D  24.4
8   Merc 230  22.8
9   Merc 280  19.2

In [11]:
df[df['car_name'].str.endswith("Drive")]

         car_name   mpg
3  Hornet 4 Drive  21.4

In [13]:
# Replace Strings
df['car_name_updated'] = df['car_name'].str.replace("Merc", "Mercedes", regex=False)
print("\nUpdated_name':\n",df[['car_name','car_name_updated']])

Updated_name':
                 car_name       car_name_updated
0              Mazda RX4              Mazda RX4
1       Mazda RX4    Wag       Mazda RX4    Wag
2             Datsun 710             Datsun 710
3         Hornet 4 Drive         Hornet 4 Drive
4  Hornet   Sportabout    Hornet   Sportabout
5                Valiant                Valiant
6             Duster 360             Duster 360
7              merc 240D              merc 240D
8               Merc 230           Mercedes 230
9               Merc 280           Mercedes 280

In [15]:
df['car_name'].str.replace("Merc", "Mercedes", case=False, regex=False)

0                Mazda RX4
1         Mazda RX4    Wag
2               Datsun 710
3           Hornet 4 Drive
4    Hornet   Sportabout
5                  Valiant
6               Duster 360
7            Mercedes 240D
8             Mercedes 230
9             Mercedes 280
Name: car_name, dtype: object

In [17]:
df['car_name'].str.replace("Merc", "Mercedes", case=True, regex=True)

0                Mazda RX4
1         Mazda RX4    Wag
2               Datsun 710
3           Hornet 4 Drive
4    Hornet   Sportabout
5                  Valiant
6               Duster 360
7                merc 240D
8             Mercedes 230
9             Mercedes 280
Name: car_name, dtype: object

In [21]:
# Split /Breaks
df['brand']= df['car_name'].str.split().str[0]
print("\nExtracted Brand':\n",df[['car_name','brand']])
#👉 Very useful for: * extracting categories, * feature engineering

Extracted Brand':
                 car_name    brand
0              Mazda RX4    Mazda
1       Mazda RX4    Wag    Mazda
2             Datsun 710   Datsun
3         Hornet 4 Drive   Hornet
4  Hornet   Sportabout     Hornet
5                Valiant  Valiant
6             Duster 360   Duster
7              merc 240D     merc
8               Merc 230     Merc
9               Merc 280     Merc

In [23]:
df['upper_name'] = df['car_name'].str.upper()
df['lower_name'] = df['car_name'].str.lower()
df

,car_name,mpg,car_name_updated,brand,upper_name,lower_name
0,Mazda RX4,21.0,Mazda RX4,Mazda,MAZDA RX4,mazda rx4
1,Mazda RX4 Wag,21.0,Mazda RX4 Wag,Mazda,MAZDA RX4 WAG,mazda rx4 wag
2,Datsun 710,22.8,Datsun 710,Datsun,DATSUN 710,datsun 710
3,Hornet 4 Drive,21.4,Hornet 4 Drive,Hornet,HORNET 4 DRIVE,hornet 4 drive
4,Hornet Sportabout,18.7,Hornet Sportabout,Hornet,HORNET SPORTABOUT,hornet sportabout
5,Valiant,18.1,Valiant,Valiant,VALIANT,valiant
6,Duster 360,14.3,Duster 360,Duster,DUSTER 360,duster 360
7,merc 240D,24.4,merc 240D,merc,MERC 240D,merc 240d
8,Merc 230,22.8,Mercedes 230,Merc,MERC 230,merc 230
9,Merc 280,19.2,Mercedes 280,Merc,MERC 280,merc 280

In [ ]:
# Cleaning (trim spaces)
df['clean_name'] = df['car_name'].str.strip()
df

In [24]:
df['clean_name'] = df['car_name'].str.strip()
df

,car_name,mpg,car_name_updated,brand,upper_name,lower_name,clean_name
0,Mazda RX4,21.0,Mazda RX4,Mazda,MAZDA RX4,mazda rx4,Mazda RX4
1,Mazda RX4 Wag,21.0,Mazda RX4 Wag,Mazda,MAZDA RX4 WAG,mazda rx4 wag,Mazda RX4 Wag
2,Datsun 710,22.8,Datsun 710,Datsun,DATSUN 710,datsun 710,Datsun 710
3,Hornet 4 Drive,21.4,Hornet 4 Drive,Hornet,HORNET 4 DRIVE,hornet 4 drive,Hornet 4 Drive
4,Hornet Sportabout,18.7,Hornet Sportabout,Hornet,HORNET SPORTABOUT,hornet sportabout,Hornet Sportabout
5,Valiant,18.1,Valiant,Valiant,VALIANT,valiant,Valiant
6,Duster 360,14.3,Duster 360,Duster,DUSTER 360,duster 360,Duster 360
7,merc 240D,24.4,merc 240D,merc,MERC 240D,merc 240d,merc 240D
8,Merc 230,22.8,Mercedes 230,Merc,MERC 230,merc 230,Merc 230
9,Merc 280,19.2,Mercedes 280,Merc,MERC 280,merc 280,Merc 280